#!/usr/bin/env python3
"""Build README.md and categories/*.md from data/. Edit the data, not the generated pages.

Usage: python3 scripts/build_readme.py [--check]
--check exits 1 if a generated page is out of date (used by CI).
"""
import csv
import io
import json
import os
import re
import sys
import urllib.parse

REPO = "vitalikgpt/gram-ecosystem"
TOP_REACH = 12
PROBLEMS = "reports/link-check.md"
SOURCES = {
    "gramnews-apps": "the [Gram News apps library](https://gramnews.org/apps)",
    "ton.app": "the [ton.app](https://ton.app) catalogue, full sitemap",
    "dyor.io": "the [DYOR](https://dyor.io) catalogue",
    "findmini": "the [FindMini](https://www.findmini.app) catalogue, TON-related mini apps only",
    "defillama": "[DefiLlama](https://defillama.com/chain/ton), protocols with TVL on TON",
    "tonapi-whitelist": "the [tonapi](https://tonapi.io) token whitelist, from a $100K market cap or 1,000 holders",
    "ton-channel-posts": "bots and product channels linked by at least three different TON channels "
    "(`metric` says how many)",
    "gramnews-feed": "a post on [@gramnews](https://t.me/gramnews)",
    "gramnews-corpus": "the Gram News post corpus: 531.7 million Telegram posts since 2015, names mentioned "
    "by at least three TON channels, then checked by hand",
    "gramnews-orgs": "studio, fund and accelerator portfolios, each link with its source",
    "telegram-similar": "Telegram's own similar channels and similar bots next to TON projects (June 2026), "
    "recommended next to at least three of them, then checked by hand",
    "gramnews-q3-2026": "the [Gram News quarterly map](reports/2026-q3)",
    "ton-society-ecosystem-map": "[ton-society/ecosystem-map](https://github.com/ton-society/ecosystem-map)",
    "awesome-ton": "[ton-community/awesome-ton](https://github.com/ton-community/awesome-ton)",
}
GENERATED = "<!-- Generated by scripts/build_readme.py from data/. Do not edit by hand. -->"


def fmt(n):
    n = int(float(n)) if n not in ("", None) else 0
    if n >= 1_000_000:
        return f"{n / 1e6:.1f}M".replace(".0M", "M")
    if n >= 1_000:
        return f"{n / 1e3:.0f}K"
    return str(n) if n else ""


def cell(s):
    return (s or "").replace("|", "/").replace("[", "(").replace("]", ")")


def short(s):
    """The description as written; no cutting to fit (a sentence with its end lopped off says less than none)."""
    return cell(s)


def home(r):
    """Where a project lives: its channel, else its bot, its site (if it answers) or its X."""
    return r["telegram"] or r["bot"] or (r["website"] if not r.get("website_down") else "") or r["x"]


def plink(r):
    url = home(r)
    return f"[{cell(r['name'])}]({url})" if url else cell(r["name"])


EMOJI = re.compile("[\U0001F000-\U0001FAFF\u2600-\u27BF\u2B00-\u2BFF\uFE0F\u200d]")


def tname(s):
    """A channel title as a name: no emoji, no «Name / slogan / slogan» tail."""
    s = EMOJI.sub("", s or "")
    s = re.split(r"\s+(?:/|\||•|—|-)\s+", s)[0]
    return cell(re.sub(r"\s+", " ", s).strip(" -|•/"))


def badge(label, value, color="5aa9ff"):
    q = lambda t: urllib.parse.quote(str(t).replace("-", "--").replace("_", "__"))
    return f"https://img.shields.io/badge/{q(label)}-{q(value)}-{color}?style=flat-square"


def verified(r):
    """«since 2023-10» when the Web Archive dates the badge, «yes» when it is there but undated."""
    if r.get("verified") != "1":
        return ""
    return f"since {r['verified_since'][:7]}" if r.get("verified_since") else "yes"


def links(r):
    out = []
    for key, label in (("telegram", "Telegram"), ("bot", "Bot"), ("x", "X"), ("website", "Site"), ("github", "GitHub"),
                       ("gramnews", "Gram News")):
        if key == "website" and r.get("website_down"):
            out.append("Site (down)")   # the address stays in the data; a dead domain is often resold, so no link
        elif r.get(key):
            out.append(f"[{label}]({r[key]})")
    return " ".join(out)








def table(items, prefix=""):
    out = ["| # | Project | What it is | Links | Launched | Peak MAU | Verified |",
           "| ---: | --- | --- | --- | --- | ---: | --- |"]
    for r in items:
        peak = fmt(r["peak_mau"]) if r.get("peak_mau") else ""
        out.append(f"| {r['rank']} | **{cell(r['name'])}** | {short(r['description'])} | {links(r)} | {r.get('launched', '')} | {peak} | {verified(r)} |")
    return out


def reach_n(r):
    try:
        return int(float(r["reach_q3"] or 0)) or int(float(r["mau"] or 0))
    except ValueError:
        return 0


INTS = {"rank", "subscribers", "reach_q3", "views_q3", "posts_q3", "mau", "peak_mau", "telegram_id", "bot_id", "on_map",
        "native", "verified", "hits", "posts", "views", "position"}
DATES = {"last_post", "last_commit", "website_down", "peak_mau_date", "verified_since", "seen", "date"}
ABOUT = {
    "projects": "TON and Telegram projects, one per row, with links, ids, activity and launch dates",
    "channels": "channels that write about TON without being a project's own",
    "similar": "whom Telegram shows in similar channels or similar bots next to an entity here (June 2026)",
    "relations": "which studio built, fund backed or accelerator took a project, with the source",
    "link-fixes": "every link decision with its evidence",
    "merged": "rows folded into the row that shares their Telegram account",
    "usernames": "other usernames of the same Telegram accounts, matched by numeric id",
    "unresolved": "names from old ecosystem maps not tied to a project yet",
}


def datapackage():
    """Frictionless Data descriptor: what each file is and what each column holds, so tools can load the set as typed tables."""
    res = []
    for name, about in ABOUT.items():
        path = f"data/{name}.csv"
        if not os.path.exists(path):
            continue
        cols = next(csv.reader(open(path, encoding="utf-8")))
        res.append({"name": name, "path": path, "format": "csv", "mediatype": "text/csv", "encoding": "utf-8", "description": about,
                    "schema": {"fields": [{"name": c, "type": "integer" if c in INTS else "string" if c not in DATES else "string",
                                           **({"description": "YYYY-MM-DD"} if c in DATES else {})} for c in cols]}})
    return json.dumps({
        "name": "gram-ecosystem",
        "title": "Gram Ecosystem: TON and Telegram projects",
        "homepage": f"https://github.com/{REPO}",
        "licenses": [{"name": "CC-BY-4.0", "path": "https://creativecommons.org/licenses/by/4.0/", "title": "Creative Commons Attribution 4.0"}],
        "contributors": [{"title": "Gram News", "path": "https://gramnews.org", "role": "author"}],
        "resources": res,
    }, indent=1, ensure_ascii=False) + "\n"


def build():
    cats = json.load(open("data/categories.json", encoding="utf-8"))
    rows = list(csv.DictReader(open("data/projects.csv", encoding="utf-8")))
    chans = list(csv.DictReader(open("data/channels.csv", encoding="utf-8")))
    unresolved = list(csv.DictReader(open("data/unresolved.csv", encoding="utf-8")))
    by = {}
    for r in rows:
        by.setdefault(r["category"], []).append(r)
    for v in by.values():
        v.sort(key=lambda r: int(r["rank"]))
    count = lambda st, items=rows: sum(1 for r in items if r["status"] == st)
    label = {c["key"]: c["label"] for c in cats}
    try:
        problems = sum(1 for l in open(PROBLEMS, encoding="utf-8") if l.startswith("| ") and not l.startswith("| Project") and not l.startswith("| ---"))
    except FileNotFoundError:
        problems = 0
    try:
        fixes = list(csv.DictReader(open("data/link-fixes.csv", encoding="utf-8")))
    except FileNotFoundError:
        fixes = []
    fixed = sum(1 for f in fixes if f["action"] != "confirm")
    maps = sorted(f[:-4] for f in os.listdir("archive") if f.endswith(".jpg"))
    links_total = sum(1 for r in rows for k in ("telegram", "bot", "x", "website", "github") if r[k])

    pages = {}
    badges = [
        ("projects", f"{len(rows):,}", "5aa9ff"), ("active", f"{count('active'):,}", "4cd08a"),
        ("categories", len(cats), "5aa9ff"), ("channels", f"{len(chans):,}", "5aa9ff"), ("links fixed", f"{fixed:,}", "f2b84b"),
        ("data", "CC BY 4.0", "lightgrey"),
    ]
    out = [
        GENERATED,
        "",
        '<img src="assets/cover.jpg" alt="Gram Ecosystem: TON and Telegram projects" width="100%">',
        "",
        " ".join(f'<img src="{badge(a, b, c)}" alt="{a}: {b}">' for a, b, c in badges)
        + f' <a href="https://github.com/{REPO}/actions/workflows/check.yml"><img src="https://github.com/{REPO}/actions/workflows/check.yml/badge.svg" alt="data check"></a>',
        "",
        f"**Every TON and Telegram project we could verify: {len(rows):,} of them in {len(cats)} categories, "
        "each with its channel, bot, X, site and GitHub, and the numbers that show whether it is alive.** "
        f"The {links_total:,} links are checked every week; {fixed:,} wrong ones have been fixed so far, each with its evidence.",
        "",
        "Maintained by [Gram News](https://gramnews.org). Open data: take it, fix it, build on it.",
        "",
        *([f"**This week**: " + ", ".join(t for n, t in ((wk["added"], f"{wk['added']:,} new projects"), (wk["woke"], f"{wk['woke']:,} became active"),
                                                         (wk["badge"], f"{wk['badge']:,} got the verified badge"), (wk["channels"], f"{wk['channels']:,} new channels")) if n)
           + f"; [the weekly summary]({wk['path']}) has the names, [earlier weeks](reports/weekly/README.md) too.", ""]
          if (wk := (json.load(open("reports/weekly/latest.json")) if os.path.exists("reports/weekly/latest.json") else None)) else []),
        "**Browse it right here**: every category opens as a searchable table, its *table* link below; "
        "so do [channels](data/channels.csv) and [studios and funds](data/relations.csv).",
        "",
        "**Jump to** [Categories](#categories), [Largest projects](#largest-projects), [Neighbours on Telegram](#neighbours-on-telegram), [Verified](#verified-on-telegram), [Other usernames](#other-usernames), "
        "[Studios and funds](#studios-funds-and-accelerators), [Channels](#channels), [How to read it](#how-to-read-it), "
        "[Data](#data), [Maps and reports](#maps-and-reports), [Contribute](#contribute)",
        "",
        "## Categories",
        "",
        "Each category has its own page with every project, active ones first.",
        "",
        "| Category | Active | All | Notable projects | Table |",
        "| --- | ---: | ---: | --- | --- |",
    ]
    for c in cats:
        items = by.get(c["key"], [])
        act = [r for r in items if r["status"] == "active"]
        pick = act
        if c["key"] in ("studios", "funds", "accelerators"):   # the portfolio organisations, not whoever posted most
            nrel = {}
            for x in (csv.DictReader(open("data/relations.csv", encoding="utf-8")) if os.path.exists("data/relations.csv") else []):
                nrel[x["organisation_slug"]] = nrel.get(x["organisation_slug"], 0) + 1
            pick = sorted(items, key=lambda r: (-nrel.get(r["slug"], 0), "gramnews-orgs" not in r["sources"], int(r["rank"])))
        out.append(f"| [{c['label']}](categories/{c['key']}.md) | {len(act)} | {len(items)} | {', '.join(plink(r) for r in pick[:4])} | [table](data/by-category/{c['key']}.csv) |")
    # what the ecosystem is made of: the nine largest categories and the rest as one slice
    sizes = sorted(((label[c["key"]], len(by.get(c["key"], []))) for c in cats), key=lambda kv: -kv[1])
    out += ["", "```mermaid", "pie showData", '  title What the catalogue is made of']
    out += [f'  "{n}" : {v}' for n, v in sizes[:9]]
    out += [f'  "Other {len(sizes) - 9} categories" : {sum(v for _, v in sizes[9:])}', "```"]
    top = sorted((r for r in rows if r["status"] == "active" and r["category"] not in ("tokens", "nftcaps")),
                 key=reach_n, reverse=True)[:TOP_REACH]
    out += [
        "",
        "## Largest projects",
        "",
        "By reach: post views on the project's own channel from July to September 2026, or its bot's monthly users, "
        "whichever is larger.",
        "",
        "| Project | Category | Reach | Peak MAU | Launched | Verified |",
        "| --- | --- | ---: | ---: | --- | --- |",
    ]
    for r in top:
        out.append(f"| {plink(r)} | [{label[r['category']]}](categories/{r['category']}.md) | {fmt(reach_n(r))} | "
                   f"{fmt(r['peak_mau']) if r.get('peak_mau') else ''} | {r['launched'][:7]} | {verified(r)} |")
    # launches per quarter: the ecosystem's history in one picture; the quarter in progress is left out
    import datetime as _dt
    today = _dt.date.today()
    cur = f"{today.year}Q{(today.month - 1) // 3 + 1}"
    qs = {}
    for r in rows:
        l = r["launched"]
        if len(l) >= 7:
            k = f"{l[:4]}Q{(int(l[5:7]) - 1) // 3 + 1}"
            qs[k] = qs.get(k, 0) + 1
    keys = [k for k in sorted(qs) if "2021Q1" <= k < cur]
    peak = max(keys, key=lambda k: qs[k])
    out += [
        "",
        "## Launches by quarter",
        "",
        f"When the {sum(qs[k] for k in keys):,} projects with a known launch month started or came to TON. "
        f"The busiest quarter was {peak[4:]} {peak[:4]} with {qs[peak]:,}.",
        "",
        "```mermaid",
        '%%{init: {"xyChart": {"width": 1000, "height": 300}, "themeVariables": {"xyChart": {"plotColorPalette": "#2f81f7"}}}}%%',
        "xychart-beta",
        "  x-axis [" + ", ".join(f'\"{k[2:4]}{k[4:]}\"' for k in keys) + "]",
        '  y-axis "Projects launched"',
        "  bar [" + ", ".join(str(qs[k]) for k in keys) + "]",
        "```",
    ]
    # when Telegram gave the badge: the largest dated accounts per year, from the Web Archive
    ver = {}
    for r in sorted((r for r in rows if r.get("verified_since") and r["category"] != "tokens"), key=reach_n, reverse=True):
        ver.setdefault(r["verified_since"][:4], []).append(r["name"].replace(":", " ").replace("#", ""))
    if len(ver) >= 3:
        out += [
            "",
            "## Verified on Telegram",
            "",
            f"{sum(1 for r in rows if r.get('verified') == '1'):,} projects carry Telegram's badge. For "
            f"{sum(1 for r in rows if r.get('verified_since')):,} of them the Web Archive shows when it appeared; the largest of each year:",
            "",
            "```mermaid",
            "timeline",
        ]
        out += [f"  {y} : " + " : ".join(ver[y][:4]) for y in sorted(ver)]
        out += ["```"]
    # who Telegram shows next to the largest projects: the top of their similar lists, both sides in this dataset
    sim = list(csv.DictReader(open("data/similar.csv", encoding="utf-8"))) if os.path.exists("data/similar.csv") else []
    by_url = {}
    for r in rows:
        for k in ("telegram", "bot"):
            if r[k]: by_url.setdefault(r[k], r)
    for c in chans:
        by_url.setdefault(c["telegram"], dict(name=c["name"], telegram=c["telegram"], bot="", website="", x=""))
    nexts = {}
    for e in sim:
        nexts.setdefault(e["from"], []).append(e)
    shown = []
    for r in sorted((r for r in rows if r["category"] != "tokens"), key=reach_n, reverse=True):   # a token beside its own project would show twice
        es = sorted(nexts.get(r["telegram"], []) + nexts.get(r["bot"], []), key=lambda e: int(e["rank"]))
        es = [e for e in es if by_url.get(e["to"]) is not r]
        if len(es) >= 3:
            shown.append((r, es[:4]))
        if len(shown) == 10:
            break
    out += [
        "",
        "## Neighbours on Telegram",
        "",
        "Whom Telegram itself puts in *similar channels* and *similar bots* next to the largest projects, in its order. "
        "It picks them by overlapping audiences, so this is who shares the crowd, not who sends traffic. "
        f"All {len(sim):,} pairs are in [data/similar.csv](data/similar.csv) (snapshot of June 2026).",
        "",
        "| Project | Shown next to it |",
        "| --- | --- |",
    ]
    for r, es in shown:
        out.append(f"| {plink(r)} | " + ", ".join(plink(by_url[e['to']]) if e["to"] in by_url else cell(e["to_name"]) for e in es) + " |")
    # other usernames of the same accounts, matched by Telegram's numeric id
    uns = list(csv.DictReader(open("data/usernames.csv", encoding="utf-8"))) if os.path.exists("data/usernames.csv") else []
    if uns:
        reach_of = {}
        for r in rows:
            for k in ("telegram", "bot"):
                if r[k]: reach_of[r[k]] = max(reach_of.get(r[k], 0), reach_n(r))
        moved = sorted((u for u in uns if u["kind"] != "also known as"), key=lambda u: -reach_of.get(u["now"], 0))
        aka = {}
        for u in uns:
            if u["kind"] == "also known as":
                aka.setdefault(u["now"], []).append(u)
        out += [
            "",
            "## Other usernames",
            "",
            f"Telegram's numeric id outlives a username, so the same account can be followed across names. "
            f"{len(aka):,} accounts here hold more than one username ({sum(len(v) for v in aka.values()):,} extra names, mostly collectible ones), "
            f"and {len(moved)} moved to a new name. All pairs are in [data/usernames.csv](data/usernames.csv).",
            "",
            "| Account | Now | Was |",
            "| --- | --- | --- |",
        ]
        for u in moved[:10]:
            out.append(f"| {cell(u['name'])} | [@{u['now'].rsplit('/', 1)[-1]}]({u['now']}) | @{u['other'].rsplit('/', 1)[-1]}"
                       + (" (now another account)" if u["kind"] == "name taken" else " (free)") + " |")
        out += ["", "| Account | Also answers to |", "| --- | --- |"]
        for now, us in sorted(aka.items(), key=lambda kv: -reach_of.get(kv[0], 0))[:10]:
            out.append(f"| [{cell(us[0]['name'])}]({now}) | " + ", ".join(f"[@{x['other'].rsplit('/', 1)[-1]}]({x['other']})" for x in us[:8])
                       + (f" and {len(us) - 8} more" if len(us) > 8 else "") + " |")
    out += [
        "",
        "## Studios, funds and accelerators",
        "",
        "Who builds and backs the projects. Each link between a project and an organisation is in "
        "[data/relations.csv](data/relations.csv) with the page that states it.",
        "",
        "| Organisation | Type | Projects | Sources |",
        "| --- | --- | --- | --- |",
    ]
    rels = list(csv.DictReader(open("data/relations.csv", encoding="utf-8"))) if os.path.exists("data/relations.csv") else []
    kind = {"studios": "studio", "funds": "fund", "accelerators": "accelerator"}
    verb = {"built by": "built", "published by": "published", "invested by": "invested", "subsidiary of": "parent company",
            "first cohort of": "first cohort", "part of": "owns", "part of the ecosystem of": "ecosystem", "launched by": "co-launched",
            "venture arm of": "venture arm"}
    for r in sorted((r for r in rows if r["category"] in kind), key=lambda r: (list(kind).index(r["category"]), -sum(1 for x in rels if x["organisation_slug"] == r["slug"]), r["name"])):
        mine = [x for x in rels if x["organisation_slug"] == r["slug"]]
        if not mine:
            continue
        by_slug = {p["slug"]: p for p in rows}
        groups = {}
        for x in mine:
            groups.setdefault(verb.get(x["relation"], x["relation"]), []).append(x)
        srcs = list(dict.fromkeys(x["source"] for x in mine))
        cellp = "; ".join(f"{v}: " + ", ".join(plink(by_slug[x["project_slug"]]) if x["project_slug"] in by_slug else cell(x["project"]) for x in xs)
                          for v, xs in groups.items())
        out.append(f"| {plink(r)} | {kind[r['category']]} | {cellp} | "
                   + " ".join(f"[{i}]({u})" for i, u in enumerate(srcs, 1)) + " |")
    # the same relations as a picture: organisations on the left, what they built or backed on the right;
    # a project tied to several organisations is one node, so the web shows
    rels_g = list(csv.DictReader(open("data/relations.csv", encoding="utf-8"))) if os.path.exists("data/relations.csv") else []
    nrel_g = {}
    for x in rels_g:
        nrel_g[x["organisation_slug"]] = nrel_g.get(x["organisation_slug"], 0) + 1
    ids = {}
    def node(slug, name, org):
        if slug not in ids:
            ids[slug] = (f"o{len(ids)}" if org else f"p{len(ids)}", name.replace('"', "'"), org)
        return ids[slug][0]
    edges = []
    for x in rels_g:
        if nrel_g[x["organisation_slug"]] < 2:
            continue
        o = node(x["organisation_slug"], x["organisation"], True)
        q = node(x["project_slug"], x["project"], x["project_slug"] in nrel_g)
        v = verb.get(x["relation"], x["relation"])
        arrow = "==>" if v in ("built", "published", "owns") else "-.->" if v == "invested" else "-->"   # the line says the relation
        edges.append(f"  {o} {arrow} {q}")
    if edges:
        out += ["", "The same links as a web. Organisations are blue; a thick line means built or published, a dotted one invested, "
                "a thin one any other tie; a project tied to several organisations is drawn once.", "", "```mermaid", "flowchart LR"]
        out += [f'  {i}(["{n}"])' if org else f'  {i}["{n}"]' for i, n, org in ids.values()]
        out += edges
        out += ["  classDef org fill:#1f6feb,color:#fff,stroke:#1f6feb",
                "  class " + ",".join(i for i, n, org in ids.values() if org) + " org", "```", ""]
    out += [
        "",
        "## How to read it",
        "",
        "- **Status** is measured, not judged: `active`, `quiet` or `closed`.",
        "- **Launched** is when the project started or came to TON; `launched_source` says how the date was found.",
        "",
        "<details><summary><b>What makes a project active</b></summary>",
        "",
        "At least one of these held from July 1 to September 30, 2026:",
        "",
        "1. its own Telegram channel published a post;",
        "2. its bot showed 1,000+ monthly users on its t.me page;",
        "3. Gram News wrote about it;",
        "4. it had $10,000+ of TVL on TON on DefiLlama;",
        "5. for developer tools and infrastructure, its GitHub repository received a commit.",
        "",
        "Otherwise it is `quiet`, with its links kept. `closed` means the source catalogue marked it as shut down, "
        "or every link it had is dead: the username is free on t.me, the domain no longer resolves, the repository is gone.",
        "",
        "A channel or bot counts for a project only if it matches the project by name: catalogues often carry someone else's.",
        "",
        "</details>",
        "",
        "<details><summary><b>Where the projects come from</b></summary>",
        "",
        "The `sources` column lists every place a project was found:",
        "",
    ]
    for k, v in SOURCES.items():
        out.append(f"- `{k}`: {v};")
    out += [
        "- a date and an author, such as `2024-06-dwf-ventures`: an ecosystem map in the [archive](archive).",
        "",
        "</details>",
        "",
        "## Data",
        "",
        "| File | What is in it |",
        "| --- | --- |",
        f"| [data/projects.csv](data/projects.csv) | {len(rows):,} projects, one per row |",
        f"| [data/channels.csv](data/channels.csv) | {len(chans):,} channels about TON that are not a project's own, with language, theme, creation date, posts and views |",
        "| [data/categories.json](data/categories.json) | categories in display order |",
        f"| [data/link-fixes.csv](data/link-fixes.csv) | {len(fixes):,} link decisions (replaced, removed, confirmed, marked down) with evidence |",
        "| [datapackage.json](datapackage.json) | the [Frictionless](https://frictionlessdata.io) descriptor: every file and column, for tools that load typed tables |",
        f"| [data/usernames.csv](data/usernames.csv) | {sum(1 for _ in open('data/usernames.csv')) - 1 if os.path.exists('data/usernames.csv') else 0} other usernames of the same accounts, by numeric id: second names, renames, names now held by someone else |",
        f"| [data/merged.csv](data/merged.csv) | {sum(1 for _ in open('data/merged.csv')) - 1 if os.path.exists('data/merged.csv') else 0} rows folded into the row that shares their Telegram account (the numeric id), with the key |",
        f"| [data/unresolved.csv](data/unresolved.csv) | {len(unresolved)} names from old maps not tied to a project yet |",
        "| [data/relations.csv](data/relations.csv) | which studio built, fund backed or accelerator took each project, with the source |",
        f"| [data/similar.csv](data/similar.csv) | {sum(1 for _ in open('data/similar.csv')) - 1:,} pairs: whom Telegram shows in similar channels or similar bots next to an entity here, with the position (June 2026); audiences overlap, it is not traffic |",
        f"| [{PROBLEMS}]({PROBLEMS}) | {problems:,} links that failed the last check |",
        "",
        "<details><summary><b>Columns of projects.csv</b></summary>",
        "",
        "`category`, `rank`, `name`, `slug`, `status`, `on_map`, `native`, `evidence`, `telegram`, `bot`, `x`, `website`, `website_down` (the date a check found the site gone), "
        "`telegram_id` and `bot_id` (Telegram's numeric ids, which survive a rename), `verified` and `verified_since` "
        "(the badge on t.me, and the first Web Archive copy of its page that shows it; empty when the archive does not date it), "
        "`peak_mau` and `peak_mau_date` (the highest monthly users on the FindMini chart, which starts in July 2024; "
        "a peak on the chart's first day may have been higher before it), "
        "`github`, `gramnews` (the project's card on gramnews.org), `last_post`, `last_commit`, `launched`, `launched_source`, `subscribers`, "
        "`reach_q3`, `views_q3`, `posts_q3`, `mau`, `metric`, `sources`, `description`.",
        "",
        "</details>",
        "",
        "<details><summary><b>How launch dates are found</b></summary>",
        "",
        "Every project has a `launched` date: when it started, or when an existing company came to TON. "
        "Precision is `YYYY-MM-DD`, `YYYY-MM` for estimates, or `YYYY` when only the year is known. "
        "The earliest of these signals wins, and `launched_source` names it:",
        "",
        "- its own channel was created (post number one on t.me), or its bot was first mentioned in another channel, "
        "from the Gram News archive of 531.7 million Telegram posts since 2015;",
        "- the jetton was minted, the GitHub repository was created, the protocol was listed on DefiLlama;",
        "- an existing company came to TON: the first post on its own channel that names TON, when that is half a year or more after launch;",
        "- a catalogue listing: the Gram News library, or the month estimated from a project's number in the ton.app or DYOR catalogue "
        "(median error 46 days);",
        "- otherwise a lower bound, worded as such: the earliest ecosystem map, commit or post that shows the project already existed;"
        " and, as a last resort, the X account or the domain registration.",
        "",
        "For games, farming, NFT, casinos and memepads, dates before January 2018 are ignored when a later signal exists: "
        "they belong to an older channel or a username taken over.",
        "",
        "</details>",
        "",
        "## Maps and reports",
        "",
        "- [**Gram News map, Q3 2026**](reports/2026-q3): the quarterly poster in English and Russian, with the methodology, "
        "and the [article with leaderboards](https://gramnews.org/articles/ton-ecosystem-map-q3-2026).",
        f"- [**Archive of {len(maps)} ecosystem maps**](archive) by Messari, DWF, Coin98, Tonstarter, TON CIS Hub and others, 2022 to 2026.",
        "",
        "## Channels",
        "",
        f"{len(chans):,} channels write about TON without being a project's own. Together they have "
        f"{fmt(sum(int(c['subscribers'] or 0) for c in chans))} subscribers and published "
        f"{sum(int(c['posts_q3'] or 0) for c in chans):,} posts with {fmt(sum(int(c['views_q3'] or 0) for c in chans))} views "
        "from July to September 2026. The full list with each channel's numbers is in [data/channels.csv](data/channels.csv).",
        "",
        "| Theme | Channels | Subscribers | Posts | Views | Largest |",
        "| --- | ---: | ---: | ---: | ---: | --- |",
    ]
    themes = {}
    for c in chans:
        themes.setdefault(c.get("theme") or "Other", []).append(c)
    for t, cs in sorted(themes.items(), key=lambda kv: -sum(int(c["views_q3"] or 0) for c in kv[1])):
        big = sorted(cs, key=lambda c: -int(c["views_q3"] or 0))[:3]
        out.append(f"| {t} | {len(cs)} | {fmt(sum(int(c['subscribers'] or 0) for c in cs))} | "
                   f"{sum(int(c['posts_q3'] or 0) for c in cs):,} | {fmt(sum(int(c['views_q3'] or 0) for c in cs))} | "
                   + ", ".join(f"[{tname(c["name"]) or c['telegram'].rsplit('/', 1)[-1]}]({c['telegram']})" for c in big) + " |")
    langs = {}
    for c in chans:
        langs[c.get("language") or "other"] = langs.get(c.get("language") or "other", 0) + 1
    names = {"ru": "Russian", "en": "English", "fa": "Persian", "uk": "Ukrainian", "ar": "Arabic", "id": "Indonesian", "zh": "Chinese"}
    out += ["", "By language: " + ", ".join(f"{names.get(k, k)} {v}" for k, v in sorted(langs.items(), key=lambda kv: -kv[1]) if v >= 3) + "."]
    out += [
        "",
        "## Contribute",
        "",
        "Found a wrong link or a missing project? Fill in a form, no files to edit: "
        "[wrong link](https://github.com/vitalikgpt/gram-ecosystem/issues/new?template=fix-link.yml), "
        "[missing project](https://github.com/vitalikgpt/gram-ecosystem/issues/new?template=add-project.yml). "
        "Pull requests are welcome too, see [CONTRIBUTING.md](CONTRIBUTING.md).",
        "",
        "## Cite",
        "",
        "GitHub's *Cite this repository* button gives the reference in APA and BibTeX ([CITATION.cff](CITATION.cff)).",
        "",
        "## License",
        "",
        "Data (`data/`, `reports/`) under [CC BY 4.0](LICENSE-DATA): reuse freely, credit Gram News. "
        "Scripts under [MIT](LICENSE). Images in `archive/` belong to their authors.",
        "",
        "Not investment advice. A listing only says a project was found and what it did; check it yourself before you use it.",
        "",
    ]
    pages["README.md"] = "\n".join(out)
    pages["datapackage.json"] = datapackage()
    # per-category slices: GitHub shows a CSV as a searchable table only while it is small, and projects.csv is not
    SLICE = ["rank", "name", "status", "description", "telegram", "bot", "x", "website", "launched", "peak_mau", "verified_since"]
    for c in cats:
        buf = io.StringIO()
        w = csv.writer(buf, lineterminator="\n")
        w.writerow(SLICE)
        for r in by.get(c["key"], []):
            w.writerow([r.get(k, "") for k in SLICE])
        pages[f"data/by-category/{c['key']}.csv"] = buf.getvalue()

    for c in cats:
        items = by.get(c["key"], [])
        act = [r for r in items if r["status"] == "active"]
        p = [
            GENERATED,
            "",
            f"# {c['label']}",
            "",
            f"**{len(items)} projects: {len(act)} active, {count('quiet', items)} quiet, {count('closed', items)} closed.** "
            "Back to [all categories](../README.md#categories); statuses are explained [here](../README.md#how-to-read-it). "
            f"The same list as a [searchable table](../data/by-category/{c['key']}.csv).",
            "",
        ]
        years = {}
        for r in items:
            if r["launched"][:4].isdigit() and r["launched"][:4] >= "2018":
                years[r["launched"][:4]] = years.get(r["launched"][:4], 0) + 1
        if len(years) >= 3:   # when the category was born and when it boomed; this year so far
            ys = [str(y) for y in range(int(min(years)), int(max(years)) + 1)]
            p += ["```mermaid", '%%{init: {"xyChart": {"width": 900, "height": 220}, "themeVariables": {"xyChart": {"plotColorPalette": "#2f81f7"}}}}%%',
                  "xychart-beta", '  title "Launched per year"', "  x-axis [" + ", ".join(f'\"{y}\"' for y in ys) + "]",
                  "  bar [" + ", ".join(str(years.get(y, 0)) for y in ys) + "]", "```", ""]
        if act:
            p += ["## Active", ""] + table(act, "../") + [""]
        for st, title in (("quiet", "Quiet"), ("closed", "Closed")):
            part = [r for r in items if r["status"] == st]
            if part:
                p += [f"<details><summary><b>{title}: {len(part)}</b></summary>", ""] + table(part, "../") + ["", "</details>", ""]
        pages[f"categories/{c['key']}.md"] = "\n".join(p)
    return pages, len(rows), len(cats)


def main():
    pages, n, nc = build()
    if "--check" in sys.argv:
        stale = [p for p, t in pages.items() if not os.path.exists(p) or open(p, encoding="utf-8").read() != t]
        if stale:
            print("Out of date: " + ", ".join(stale) + ". Run python3 scripts/build_readme.py")
            sys.exit(1)
        return
    os.makedirs("categories", exist_ok=True)
    os.makedirs("data/by-category", exist_ok=True)
    for f in os.listdir("data/by-category"):
        if f"data/by-category/{f}" not in pages:
            os.remove(f"data/by-category/{f}")
    for f in os.listdir("categories"):
        if f"categories/{f}" not in pages:
            os.remove(f"categories/{f}")
    for p, t in pages.items():
        open(p, "w", encoding="utf-8").write(t)
    print(f"README.md and {len(pages) - 1} category pages: {n} projects, {nc} categories")


if __name__ == "__main__":
    main()
