#!/usr/bin/env python3
"""Build README.md from data/*.csv. Edit the data, not the README.

Usage: python3 scripts/build_readme.py [--check]
--check exits 1 if README.md is out of date (used by CI).
"""
import csv
import json
import re
import sys

CHANNELS_SHOWN = 50
PROBLEMS = "reports/link-check.md"


def fmt(n):
    n = int(float(n)) if n not in ("", None) else 0
    if n >= 1_000_000:
        return f"{n / 1e6:.1f}M".replace(".0M", "M")
    if n >= 1_000:
        return f"{n / 1e3:.0f}K"
    return str(n) if n else ""


def anchor(text):
    return re.sub(r"[^a-z0-9 -]", "", text.lower()).replace(" ", "-")


def links(r):
    out = []
    for key, label in (("telegram", "Telegram"), ("bot", "Bot"), ("x", "X"), ("website", "Website")):
        if r[key]:
            out.append(f"[{label}]({r[key]})")
    return " ".join(out)


def signal(r):
    if r["metric"]:
        return r["metric"]
    parts = []
    if r["views_q3"]:
        parts.append(f"{fmt(r['views_q3'])} views")
    if r["mau"]:
        parts.append(f"{fmt(r['mau'])} MAU")
    return ", ".join(parts)


def main():
    cats = json.load(open("data/categories.json", encoding="utf-8"))
    rows = list(csv.DictReader(open("data/projects.csv", encoding="utf-8")))
    chans = list(csv.DictReader(open("data/channels.csv", encoding="utf-8")))
    by = {}
    for r in rows:
        by.setdefault(r["category"], []).append(r)
    for v in by.values():
        v.sort(key=lambda r: int(r["rank"]))

    native = sum(1 for r in rows if r["native"] == "1")
    try:
        problems = sum(1 for l in open(PROBLEMS, encoding="utf-8") if l.startswith("| ") and not l.startswith("| Project") and not l.startswith("| ---"))
    except FileNotFoundError:
        problems = 0

    out = [
        "<!-- Generated by scripts/build_readme.py from data/. Do not edit by hand. -->",
        "",
        "# Gram Ecosystem",
        "",
        "A library of Gram (TON) and core Telegram projects, grouped by what they do, with links and the numbers "
        "that show each one is alive. Maintained by [Gram News](https://gramnews.org).",
        "",
        '<a href="reports/2026-q3/poster-en-4k.png"><img src="reports/2026-q3/poster-en.png" alt="TON ecosystem, Q3 2026" width="100%"></a>',
        "",
        f"**{len(rows)} projects in {len(cats)} categories, {native} of them native to TON. "
        f"{len(chans)} channels about TON.** Snapshot: July 1 to September 30, 2026. "
        "Full write-up and interactive leaderboards: "
        "[gramnews.org/articles/ton-ecosystem-map-q3-2026](https://gramnews.org/articles/ton-ecosystem-map-q3-2026). "
        "Posters in English and Russian: [reports/2026-q3](reports/2026-q3).",
        "",
        f"Every link here is checked. [{problems} links currently need fixing]({PROBLEMS}): wrong accounts, dead sites, "
        "missing channels. That list is the best place to start contributing.",
        "",
        "## Contents",
        "",
        "- [How a project gets in](#how-a-project-gets-in)",
    ]
    for c in cats:
        out.append(f"- [{c['label']}](#{anchor(c['label'])}) ({len(by.get(c['key'], []))})")
    out += [
        "- [Channels](#channels)",
        "- [Data files](#data-files)",
        "- [Contributing](#contributing)",
        "- [Disclaimer](#disclaimer)",
        "- [License](#license)",
        "",
        "## How a project gets in",
        "",
        "A project is listed when at least one of these held during the quarter:",
        "",
        "1. its Telegram channel published a post;",
        "2. its X account published a post;",
        "3. Gram News covered an event of the project;",
        "4. its bot had 10,000+ monthly users, and the bot matches the project by name;",
        "5. the service itself works and shows activity: a live site, or TVL on TON (DefiLlama).",
        "",
        "The `evidence` column in [data/projects.csv](data/projects.csv) says which one applies "
        "(`telegram`, `x`, `gramnews`, `mau`, `site`, `market`); `editor` marks major brands added by hand. "
        "`native` is 1 for projects built for TON and 0 for global brands and multi-chain services.",
        "",
        "Within a category projects are ordered by reach: the larger of post views over the quarter (Telegram plus X) "
        "and the bot's monthly users. Where readers expect the big names first, they come first. "
        "Tokens are ordered by price change over the quarter, NFT collections by market cap.",
        "",
    ]
    for c in cats:
        items = by.get(c["key"], [])
        out += [f"## {c['label']}", ""]
        head = "Change" if c["key"] == "tokens" else "Market cap" if c["key"] == "nftcaps" else "Q3 signal"
        out += [f"| Project | Links | {head} | Native |", "| --- | --- | --- | :---: |"]
        for r in items:
            out.append(f"| {r['name'].replace('|', '/')} | {links(r)} | {signal(r)} | {'✓' if r['native'] == '1' else ''} |")
        out.append("")
    out += [
        "## Channels",
        "",
        f"Channels about TON that are not a project's own, by post views over the quarter. "
        f"Top {CHANNELS_SHOWN} here, all {len(chans)} in [data/channels.csv](data/channels.csv).",
        "",
        "| # | Channel | Subscribers | Posts | Views |",
        "| ---: | --- | ---: | ---: | ---: |",
    ]
    for c in chans[:CHANNELS_SHOWN]:
        out.append(f"| {c['rank']} | [{c['name'].replace('|', '/').replace('[', '(').replace(']', ')')}]({c['telegram']}) | {fmt(c['subscribers'])} | {c['posts_q3']} | {fmt(c['views_q3'])} |")
    out += [
        "",
        "## Data files",
        "",
        "- [data/projects.csv](data/projects.csv): one row per project. Columns: `category`, `rank`, `name`, `slug`, "
        "`native`, `evidence`, `telegram`, `bot`, `x`, `website`, `reach_q3`, `views_q3`, `posts_q3`, `mau`, `metric`.",
        "- [data/categories.json](data/categories.json): categories in display order.",
        "- [data/channels.csv](data/channels.csv): channels about TON with quarterly posts and views.",
        f"- [{PROBLEMS}]({PROBLEMS}): links that failed the check.",
        "",
        "## Contributing",
        "",
        "Fix a link, add a project, or move one to the right category: see [CONTRIBUTING.md](CONTRIBUTING.md). "
        "Edit `data/`, then run `python3 scripts/build_readme.py`; CI checks the rest.",
        "",
        "## Disclaimer",
        "",
        "Not investment advice. A listing is not an endorsement: it only says the project showed signs of activity "
        "in the period. Check any project yourself before you use it.",
        "",
        "## License",
        "",
        "Data (`data/`, `reports/`) under [CC BY 4.0](LICENSE-DATA): reuse freely, credit Gram News. "
        "Scripts under [MIT](LICENSE).",
        "",
    ]
    text = "\n".join(out)
    if "--check" in sys.argv:
        if open("README.md", encoding="utf-8").read() != text:
            print("README.md is out of date: run python3 scripts/build_readme.py")
            sys.exit(1)
        return
    open("README.md", "w", encoding="utf-8").write(text)
    print(f"README.md: {len(rows)} projects, {len(cats)} categories")


if __name__ == "__main__":
    main()
