#!/usr/bin/env python3
"""Build README.md and categories/*.md from data/. Edit the data, not the generated pages.

Usage: python3 scripts/build_readme.py [--check]
--check exits 1 if a generated page is out of date (used by CI).
"""
import csv
import json
import os
import re
import sys

CHANNELS_SHOWN = 50
TOP_SHOWN = 12
PROBLEMS = "reports/link-check.md"
SOURCES = {
    "gramnews-q3-2026": "[Gram News map, Q3 2026](reports/2026-q3)",
    "gramnews-apps": "the [Gram News apps library](https://gramnews.org/apps)",
    "ton.app": "[ton.app](https://ton.app) catalogue (the full sitemap, read on October 1, 2026)",
    "dyor.io": "[DYOR](https://dyor.io) catalogue",
    "findmini": "[FindMini](https://www.findmini.app) catalogue of mini apps, the TON-related ones",
    "defillama": "[DefiLlama](https://defillama.com/chain/ton), protocols on TON",
    "tonapi-whitelist": "tokens on the [tonapi](https://tonapi.io) whitelist with a $100K market cap or 1,000 holders",
    "ton-society-ecosystem-map": "[ton-society/ecosystem-map](https://github.com/ton-society/ecosystem-map)",
    "awesome-ton": "[ton-community/awesome-ton](https://github.com/ton-community/awesome-ton)",
    "gramnews-feed": "a [@gramnews](https://t.me/gramnews) post in Q3 2026",
    "ton-channel-posts": "a bot or product channel linked in posts of at least three different TON channels in Q3 2026 "
    "(the `metric` column says how many)",
}


def fmt(n):
    n = int(float(n)) if n not in ("", None) else 0
    if n >= 1_000_000:
        return f"{n / 1e6:.1f}M".replace(".0M", "M")
    if n >= 1_000:
        return f"{n / 1e3:.0f}K"
    return str(n) if n else ""


def anchor(text):
    return re.sub(r"[^a-z0-9 -]", "", text.lower()).replace(" ", "-")


def cell(s):
    return (s or "").replace("|", "/").replace("[", "(").replace("]", ")")


def links(r):
    out = []
    for key, label in (("telegram", "Telegram"), ("bot", "Bot"), ("x", "X"), ("website", "Site"), ("github", "GitHub")):
        if r[key]:
            out.append(f"[{label}]({r[key]})")
    return " ".join(out)


def signal(r):
    if r["metric"]:
        return r["metric"]
    parts = []
    if r["views_q3"]:
        parts.append(f"{fmt(r['views_q3'])} views")
    if r["mau"] and r["status"] == "active":
        parts.append(f"{fmt(r['mau'])} MAU")
    if not parts and r["last_commit"] >= "2026-07-01" and r["category"] in ("devtools", "infra", "tools"):
        parts.append(f"commit {r['last_commit']}")
    return ", ".join(parts)


def last_seen(r):
    return max(r["last_post"], r["last_commit"]) or ""


def seen_in(r, prefix=""):
    out = []
    for s in r["sources"].split():
        if os.path.exists(f"archive/{s}.jpg"):
            parts = s.split("-")
            year = parts[0] if parts[0].isdigit() else ""
            author = "-".join(p for p in parts if not p.isdigit() and p != "thumb")
            out.append(f"[{author} {year[2:]}]({prefix}archive/{s}.jpg)".replace(" ]", "]"))
    return " ".join(out)


def table(items, prefix=""):
    out = ["| # | Project | What it is | Links | Q3 signal | Last seen | On maps |", "| ---: | --- | --- | --- | --- | --- | --- |"]
    for r in items:
        desc = cell(r["description"])
        if len(desc) > 90:
            desc = desc[:89].rsplit(" ", 1)[0] + "…"
        name = cell(r["name"]) + (" ✓" if r["native"] == "1" else "")
        out.append(f"| {r['rank']} | {name} | {desc} | {links(r)} | {signal(r)} | {last_seen(r)} | {seen_in(r, prefix)} |")
    return out


def build():
    cats = json.load(open("data/categories.json", encoding="utf-8"))
    rows = list(csv.DictReader(open("data/projects.csv", encoding="utf-8")))
    chans = list(csv.DictReader(open("data/channels.csv", encoding="utf-8")))
    unresolved = list(csv.DictReader(open("data/unresolved.csv", encoding="utf-8")))
    by = {}
    for r in rows:
        by.setdefault(r["category"], []).append(r)
    for v in by.values():
        v.sort(key=lambda r: int(r["rank"]))
    count = lambda st, items=rows: sum(1 for r in items if r["status"] == st)
    on_map = sum(1 for r in rows if r["on_map"] == "1")
    try:
        problems = sum(1 for l in open(PROBLEMS, encoding="utf-8") if l.startswith("| ") and not l.startswith("| Project") and not l.startswith("| ---"))
    except FileNotFoundError:
        problems = 0
    try:
        fixes = list(csv.DictReader(open("data/link-fixes.csv", encoding="utf-8")))
    except FileNotFoundError:
        fixes = []
    fixed = sum(1 for f in fixes if f["action"] != "confirm")
    maps = sorted(f[:-4] for f in os.listdir("archive") if f.endswith(".jpg"))

    pages = {}
    out = [
        "<!-- Generated by scripts/build_readme.py from data/. Do not edit by hand. -->",
        "",
        "# Gram Ecosystem",
        "",
        "A library of Gram (TON) and core Telegram projects, grouped by what they do, with links, the numbers "
        "that show each one is alive, and the ecosystem maps it appeared on since 2022. Maintained by "
        "[Gram News](https://gramnews.org).",
        "",
        '<a href="reports/2026-q3/poster-en-4k.png"><img src="reports/2026-q3/poster-en.png" alt="TON ecosystem, Q3 2026" width="100%"></a>',
        "",
        f"**{len(rows)} projects in {len(cats)} categories: {count('active')} active in Q3 2026, "
        f"{count('quiet')} quiet, {count('closed')} closed.** {on_map} of the active ones are on the "
        "[Gram News map for Q3 2026](reports/2026-q3) "
        "([article with interactive leaderboards](https://gramnews.org/articles/ton-ecosystem-map-q3-2026)). "
        f"Plus {len(chans)} channels about TON and an [archive of {len(maps)} ecosystem maps](archive) by other authors, 2022 to 2026.",
        "",
        f"Every link here is checked. [{problems} links need a look]({PROBLEMS}) (a wrong account, a dead page, or a name that does not match), and "
        f"[{len(unresolved)} names from older maps](data/unresolved.csv) still need a project to point to. "
        "Those two lists are the best place to start contributing. "
        f"So far {fixed} links have been replaced or removed and {len(fixes) - fixed} confirmed, each with its evidence, "
        "in [data/link-fixes.csv](data/link-fixes.csv).",
        "",
        "## Contents",
        "",
        "- [Where the list comes from](#where-the-list-comes-from)",
        "- [Status](#status)",
    ]
    for c in cats:
        items = by.get(c["key"], [])
        out.append(f"- [{c['label']}](#{anchor(c['label'])}): {count('active', items)} active, {len(items)} in all")
    out += [
        "- [Channels](#channels)",
        "- [Data files](#data-files)",
        "- [Contributing](#contributing)",
        "- [Disclaimer](#disclaimer)",
        "- [License](#license)",
        "",
        "## Where the list comes from",
        "",
        "The `sources` column in [data/projects.csv](data/projects.csv) says where each project was found:",
        "",
    ]
    for k, v in SOURCES.items():
        out.append(f"- `{k}`: {v};")
    out += [
        "- a date and an author, such as `2024-06-dwf-ventures`: an ecosystem map in the [archive](archive).",
        "",
        "## Status",
        "",
        "`status` is measured, not judged. A project is `active` when at least one of these held from July 1 "
        "to September 30, 2026:",
        "",
        "1. its Telegram channel published a post;",
        "2. its bot showed 1,000+ monthly users on its t.me page;",
        "3. Gram News wrote about it;",
        "4. it had $10,000+ of TVL on TON on DefiLlama;",
        "5. for developer tools and infrastructure, its GitHub repository received a commit.",
        "",
        "Otherwise it is `quiet`: the links are kept, and `last_post` and `last_commit` say when it was last "
        "seen. `closed` means the catalogue it came from marked it as shut down, or every link the project had is dead: the username is free on t.me, the domain no longer resolves, the repository is gone (see [data/link-fixes.csv](data/link-fixes.csv)). Projects on the Q3 map passed "
        "a stricter test, described in [reports/2026-q3](reports/2026-q3), and a ✓ marks the ones built for TON.",
        "",
        "Within a category, projects on the map come first in map order, then active ones by reach (post views "
        "or monthly users), then quiet ones by the date they were last seen.",
        "",
    ]
    for c in cats:
        items = by.get(c["key"], [])
        act = [r for r in items if r["status"] == "active"]
        page = f"categories/{c['key']}.md"
        out += [f"## {c['label']}", ""]
        out += table(act[:TOP_SHOWN])
        out += ["", f"[All {len(items)} projects in {c['label']}]({page}): {len(act)} active, "
                f"{count('quiet', items)} quiet, {count('closed', items)} closed.", ""]
        p = [
            "<!-- Generated by scripts/build_readme.py from data/. Do not edit by hand. -->",
            "",
            f"# {c['label']}",
            "",
            f"[Back to the list](../README.md#{anchor(c['label'])}). {len(items)} projects: {len(act)} active in Q3 2026, "
            f"{count('quiet', items)} quiet, {count('closed', items)} closed. Statuses are explained in the "
            "[README](../README.md#status).",
            "",
        ]
        for st, title in (("active", "Active"), ("quiet", "Quiet"), ("closed", "Closed")):
            part = [r for r in items if r["status"] == st]
            if part:
                p += [f"## {title}", ""] + table(part, "../") + [""]
        pages[page] = "\n".join(p)
    out += [
        "## Channels",
        "",
        f"Channels about TON that are not a project's own, by post views over the quarter. "
        f"Top {CHANNELS_SHOWN} here, all {len(chans)} in [data/channels.csv](data/channels.csv).",
        "",
        "| # | Channel | Subscribers | Posts | Views |",
        "| ---: | --- | ---: | ---: | ---: |",
    ]
    for c in chans[:CHANNELS_SHOWN]:
        out.append(f"| {c['rank']} | [{cell(c['name'])}]({c['telegram']}) | {fmt(c['subscribers'])} | {c['posts_q3']} | {fmt(c['views_q3'])} |")
    out += [
        "",
        "## Data files",
        "",
        "- [data/projects.csv](data/projects.csv): one row per project. Columns: `category`, `rank`, `name`, `slug`, "
        "`status`, `on_map`, `native`, `evidence`, `telegram`, `bot`, `x`, `website`, `github`, `last_post`, "
        "`last_commit`, `launched`, `subscribers`, `reach_q3`, `views_q3`, `posts_q3`, `mau`, `metric`, `sources`, `description`.",
        "- [data/categories.json](data/categories.json): categories in display order.",
        "- [data/channels.csv](data/channels.csv): channels about TON with quarterly posts and views.",
        "- [data/unresolved.csv](data/unresolved.csv): names seen on ecosystem maps that are not tied to a project yet.",
        "- [data/link-fixes.csv](data/link-fixes.csv): every link that was replaced, removed or confirmed, with the evidence.",
        f"- [{PROBLEMS}]({PROBLEMS}): links that failed the check.",
        "- [archive](archive): ecosystem maps by other authors, 2022 to 2026.",
        "",
        "## Contributing",
        "",
        "Fix a link, add a project, tie a name from an old map to a project, or move one to the right category: "
        "see [CONTRIBUTING.md](CONTRIBUTING.md). Edit `data/`, then run `python3 scripts/build_readme.py`; CI checks the rest.",
        "",
        "## Disclaimer",
        "",
        "Not investment advice. A listing is not an endorsement: it only says the project was found in one of the "
        "sources above and shows what it did in the period. Check any project yourself before you use it.",
        "",
        "## License",
        "",
        "Data (`data/`, `reports/`) under [CC BY 4.0](LICENSE-DATA): reuse freely, credit Gram News. "
        "Scripts under [MIT](LICENSE). Images in `archive/` belong to their authors, see [archive](archive).",
        "",
    ]
    pages["README.md"] = "\n".join(out)
    return pages, len(rows), len(cats)


def main():
    pages, n, nc = build()
    if "--check" in sys.argv:
        stale = [p for p, t in pages.items() if not os.path.exists(p) or open(p, encoding="utf-8").read() != t]
        if stale:
            print("Out of date: " + ", ".join(stale) + ". Run python3 scripts/build_readme.py")
            sys.exit(1)
        return
    os.makedirs("categories", exist_ok=True)
    for f in os.listdir("categories"):
        if f"categories/{f}" not in pages:
            os.remove(f"categories/{f}")
    for p, t in pages.items():
        open(p, "w", encoding="utf-8").write(t)
    print(f"README.md and {len(pages) - 1} category pages: {n} projects, {nc} categories")


if __name__ == "__main__":
    main()
